# Welcome to Jekyll!
#
# Site settings

title: Obviously Awesome
description: "Brian Piercy's collection of bookmark esoterica."
email: bjpcjp@gmail.com
author: Brian Piercy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bjpcjp.github.io"

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll_social_icons
  - jekyll-paginate
  - jekyll-sitemap

social_links:
  twitter: https://twitter.com/brianpiercy
  github: https://github.com/bjpcjp
  linkedin: https://linkedin.com/in/brianpiercy

# excerpt visibility
show_excerpts: true 

# navigation links
header_pages:
  - posts-by-tag.html
  - about.html
  - behaviors.html # data-based equivalent = in devt
  - math.html # titled as algorithms
  - devops.html # was linux.html
  - gametheory.html
  - golang.html
  - ideas.html
  - language.html
  - prodmgmt.html
  - python.html 
  - ruby.html
  - semiconductors.html
  - uiux.html
  - webdev.html
  - all-posts.html
# pagination
paginate: 20

# algolia search plugin API:
algolia:
  #application_id: 0ST64V6V0J
  #index_name: jekyll
  #search_only_api_key: e850d8fbd248c7d7df4a35544f104d32
  #
  #extensions_to_index:
  #  - html
  #  - md 
  #  - txt 
    #- pdf
    #- ipynb
    #
#  nodes_to_index: 'p,div.card,div.textcard,blockquote'
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# disabled 2021/02/05
#disqus:
#  shortname: brianpiercy