# Welcome to Jekyll!
#
# Site settings

title: Obviously Awesome
description: "Brian Piercy's collection of bookmark esoterica."
email: bjpcjp@gmail.com
author: Brian Piercy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bjpcjp.github.io"

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll_social_icons
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

social_links:
  twitter: https://twitter.com/brianpiercy
  github: https://github.com/bjpcjp
  linkedin: https://linkedin.com/in/brianpiercy

# excerpt visibility
show_excerpts: true 

# navigation links
header_pages:
  - index.html # last 50 posts by date
  - posts-by-tag.html # all posts by tag
  - all-posts.html # all posts by title
  - about.html
#  - behaviors.html # moved to standalone post
#  - math.html # moved to standalone post
#  - devops.html # was linux.html # moved to standalone post
#  - gametheory.html # moved to standalone post
#  - golang.html # moved to standalone post
#  - ideas.html # moved to standalone post (as creativity)
#  - language.html # moved to standalone post
#  - prodmgmt.html # moved to standalone post
#  - python.html # moved to standalone post 
#  - ruby.html # moved to standalone post
#  - semiconductors.html # moved to standalone post
#  - uiux.html # moved to standalone post
#  - webdev.html # moved to standalone post
# pagination
paginate: 20

