# Welcome to Jekyll!
#
# Site settings

title: Obviously Awesome
description: "Brian Piercy's collection of bookmark esoterica."
email: bjpcjp@gmail.com
author: Brian Piercy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bjpcjp.github.io"

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll_social_icons
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

social_links:
  twitter: https://twitter.com/brianpiercy
  github: https://github.com/bjpcjp
  linkedin: https://linkedin.com/in/brianpiercy

# excerpt visibility
show_excerpts: true 

# navigation links
header_pages:
  - index.html # all posts by tag
  - index-by-date.html # last 50 posts by date
  - all-posts.html # all posts by title
  - about.html

# pagination
paginate: 20

