# Welcome to Jekyll!
#
# Site settings

title: Perfectly Awesome
description: "Brian Piercy's collection of bookmark esoterica."
email: bjpcjp@gmail.com
author: Brian Piercy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bjpcjp.github.io"

kramdown:
  syntax_highlighter_opts:
    disable : true

#theme: minima

plugins:
  - jekyll-feed
  - jekyll_social_icons
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

social_links:
  #twitter: https://twitter.com/brianpiercy
  github: https://github.com/bjpcjp
  linkedin: https://linkedin.com/in/brianpiercy

# excerpt visibility
show_excerpts: true 

# navigation links
header_pages:
  - index.html # all posts by date
  - posts-by-tag.html # all posts grouped by tag
  - posts-by-title.html # all posts by title
  - repos.html
  - about.html

# pagination
paginate: 50

# data files
latest_docfile: site.data.docs.doctree_l4_20250404
default_raindrop: site.data.raindrop.v20250419.rain20250419