# Welcome to Jekyll!
#
# Site settings

title: Perfectly Awesome
description: "Brian Piercy's collection of bookmark esoterica."
email: bjpcjp@gmail.com
author: Brian Piercy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bjpcjp.github.io"


plugins:
  - jekyll-feed
  - jekyll_social_icons
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

social_links:
  #twitter: https://twitter.com/brianpiercy
  github: https://github.com/bjpcjp
  linkedin: https://linkedin.com/in/brianpiercy

# excerpt visibility
show_excerpts: true 

# navigation links
header_pages:
  - index.html # all posts by date
  - chips/index.html # all posts grouped by tag
  - repos.html
  - about.html

# pagination
paginate: 50

# data files
latest_docfile: site.data.docs.doctree_l4_20250404
default_raindrop: v20250419.rain20250419

# raindrop topic files
collections:
  docs:
    output: true
    permalink: /docs/:path/
  _pdfs:
    output: true
    